// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFcG2SOSypkTDUUMjK0hIo9frWKSgdEiE',
    appId: '1:803333340987:web:56eb832911afec7818c11e',
    messagingSenderId: '803333340987',
    projectId: 'projektleki',
    authDomain: 'projektleki.firebaseapp.com',
    storageBucket: 'projektleki.firebasestorage.app',
    measurementId: 'G-B8VRPS5S5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3PVcpuv39hnxjB6gvcMnYzSk1QW4Q898',
    appId: '1:803333340987:android:82a29d3024324c3618c11e',
    messagingSenderId: '803333340987',
    projectId: 'projektleki',
    storageBucket: 'projektleki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyK-CmvFiKzUb59Ct5yY1OnI56ApdkcJU',
    appId: '1:803333340987:ios:dd656f395eecd7ba18c11e',
    messagingSenderId: '803333340987',
    projectId: 'projektleki',
    storageBucket: 'projektleki.firebasestorage.app',
    iosBundleId: 'com.example.myTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyK-CmvFiKzUb59Ct5yY1OnI56ApdkcJU',
    appId: '1:803333340987:ios:dd656f395eecd7ba18c11e',
    messagingSenderId: '803333340987',
    projectId: 'projektleki',
    storageBucket: 'projektleki.firebasestorage.app',
    iosBundleId: 'com.example.myTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFcG2SOSypkTDUUMjK0hIo9frWKSgdEiE',
    appId: '1:803333340987:web:39464bd185f2c6c918c11e',
    messagingSenderId: '803333340987',
    projectId: 'projektleki',
    authDomain: 'projektleki.firebaseapp.com',
    storageBucket: 'projektleki.firebasestorage.app',
    measurementId: 'G-TLX7DWC9KY',
  );
}
